use netuno;

create table agenteCarga (id integer not null auto_increment, login varchar(255), nome varchar(255), senha varchar(255), primary key (id));
create table agenteLogistica (id integer not null auto_increment, login varchar(255), nome varchar(255), senha varchar(255), primary key (id));
create table agentePorto (id integer not null auto_increment, login varchar(255), nome varchar(255), senha varchar(255), pertence_id integer, primary key (id));
create table agenteRota (id integer not null auto_increment, login varchar(255), nome varchar(255), senha varchar(255), primary key (id));
create table carga (id integer not null auto_increment, peso double, conteiner_id integer, agenteEmbarque_id integer, agenteDesembarque_id integer, patio_id integer, contrato_id integer, primary key (id));
create table cargalog (id integer not null auto_increment, data datetime, descricao varchar(255), carga_id integer, primary key (id));
create table conteiner (id integer not null auto_increment, primary key (id));
create table contratante (id integer not null auto_increment, login varchar(255), nome varchar(255), senha varchar(255), primary key (id));
create table contrato (id integer not null auto_increment, data_criacao datetime, situacao varchar(255), portoDestino_id integer, portoOrigem_id integer, contratante_id integer, primary key (id));
create table empresatransporte (id integer not null auto_increment, nome varchar(255), primary key (id));
create table navio (id integer not null auto_increment, nome varchar(255), primary key (id));
create table partecarga (id integer not null auto_increment, peso double, conteiner_id integer, agenteEmbarque_id integer, agenteDesembarque_id integer, patio_id integer, carga_id integer, primary key (id));
create table patio (id integer not null auto_increment, primary key (id));
create table porto (id integer not null auto_increment, nome varchar(255), primary key (id));
create table pregao (id integer not null auto_increment, abertoPor_id integer, anuncia_id integer, primary key (id));
create table represemptrans (id integer not null auto_increment, login varchar(255), nome varchar(255), senha varchar(255), representa_id integer, primary key (id));
create table requisicao (id integer not null auto_increment, data datetime, agenteCarga_id integer, conteiner_id integer, navio_id integer, agenteRota_id integer, primary key (id));
alter table agentePorto add index FK7F3D29EE5DE95A77 (pertence_id), add constraint FK7F3D29EE5DE95A77 foreign key (pertence_id) references porto (id);
alter table carga add index FK2F16BD367E6B894B5a0e7ae (conteiner_id), add constraint FK2F16BD367E6B894B5a0e7ae foreign key (conteiner_id) references conteiner (id);
alter table carga add index FK2F16BD368F4857315a0e7ae (agenteDesembarque_id), add constraint FK2F16BD368F4857315a0e7ae foreign key (agenteDesembarque_id) references agenteCarga (id);
alter table carga add index FK2F16BD3669DA4B4B5a0e7ae (patio_id), add constraint FK2F16BD3669DA4B4B5a0e7ae foreign key (patio_id) references patio (id);
alter table carga add index FK5A0E7AE32DFF069 (contrato_id), add constraint FK5A0E7AE32DFF069 foreign key (contrato_id) references contrato (id);
alter table carga add index FK2F16BD3651723E835a0e7ae (agenteEmbarque_id), add constraint FK2F16BD3651723E835a0e7ae foreign key (agenteEmbarque_id) references agenteCarga (id);
alter table cargalog add index FKFFB274D61F278D2B (carga_id), add constraint FKFFB274D61F278D2B foreign key (carga_id) references carga (id);
alter table contrato add index FKDE35131CE8F5EF7F (portoDestino_id), add constraint FKDE35131CE8F5EF7F foreign key (portoDestino_id) references porto (id);
alter table contrato add index FKDE35131C8FA3758B (contratante_id), add constraint FKDE35131C8FA3758B foreign key (contratante_id) references contratante (id);
alter table contrato add index FKDE35131C20856862 (portoOrigem_id), add constraint FKDE35131C20856862 foreign key (portoOrigem_id) references porto (id);
alter table partecarga add index FK2F16BD367E6B894Bfaa2c01c (conteiner_id), add constraint FK2F16BD367E6B894Bfaa2c01c foreign key (conteiner_id) references conteiner (id);
alter table partecarga add index FKFAA2C01C1F278D2B (carga_id), add constraint FKFAA2C01C1F278D2B foreign key (carga_id) references carga (id);
alter table partecarga add index FK2F16BD368F485731faa2c01c (agenteDesembarque_id), add constraint FK2F16BD368F485731faa2c01c foreign key (agenteDesembarque_id) references agenteCarga (id);
alter table partecarga add index FK2F16BD3669DA4B4Bfaa2c01c (patio_id), add constraint FK2F16BD3669DA4B4Bfaa2c01c foreign key (patio_id) references patio (id);
alter table partecarga add index FK2F16BD3651723E83faa2c01c (agenteEmbarque_id), add constraint FK2F16BD3651723E83faa2c01c foreign key (agenteEmbarque_id) references agenteCarga (id);
alter table pregao add index FKC594B55243F11C22 (abertoPor_id), add constraint FKC594B55243F11C22 foreign key (abertoPor_id) references agenteLogistica (id);
alter table pregao add index FKC594B552486CC404 (anuncia_id), add constraint FKC594B552486CC404 foreign key (anuncia_id) references carga (id);
alter table represemptrans add index FK9D5172C38E4FA557 (representa_id), add constraint FK9D5172C38E4FA557 foreign key (representa_id) references empresatransporte (id);
alter table requisicao add index FK904B149EB29344B (agenteCarga_id), add constraint FK904B149EB29344B foreign key (agenteCarga_id) references agenteCarga (id);
alter table requisicao add index FK904B1497E6B894B (conteiner_id), add constraint FK904B1497E6B894B foreign key (conteiner_id) references conteiner (id);
alter table requisicao add index FK904B1499D657B4B (navio_id), add constraint FK904B1499D657B4B foreign key (navio_id) references navio (id);
alter table requisicao add index FK904B149DE410A09 (agenteRota_id), add constraint FK904B149DE410A09 foreign key (agenteRota_id) references agenteRota (id);
create table hibernate_sequences ( sequence_name varchar(255),  sequence_next_hi_value integer ) ;
